# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: guildeducation/node-lambda:latest
    working_directory: ~/application-arc-approved-event-consumer
    steps:
      - checkout
      - run:
          name: 'Test'
          command: |
              npm install
              npm test
  deploy_dev:
    docker:
      - image: guildeducation/node-lambda:latest
    working_directory: ~/application-arc-approved-event-consumer
    steps:
      - checkout
      - run:
          name: 'Deploy Dev'
          command: STAGE=dev make
  deploy_prod:
    docker:
      - image: guildeducation/node-lambda:latest
    working_directory: ~/application-arc-approved-event-consumer
    steps:
      - checkout
      - run:
          name: 'Deploy Prod'
          command: STAGE=prod make

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          requires:
            - test
          filters:
            branches:
              only:
                - master