# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
dir: &dir ~/salesforce-application-state-changed-event-consumer

version: 2
jobs:
  test:
    docker:
      - image: guildeducation/node-lambda:latest
    working_directory: *dir
    steps:
      - checkout
      - run:
          name: 'NPM Authenticate'
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: 'Test'
          command: |
              npm install
              npm test
  deploy_dev:
    docker:
      - image: guildeducation/node-lambda:latest
    working_directory: *dir
    steps:
      - checkout
      - run:
          name: "Install tools"
          command: apt-get update && apt-get install -y rsync
      - run:
          name: "Setup Path"
          command: echo 'export PATH=~/.local/bin/:$PATH' >> $BASH_ENV
      - run:
          name: "Configure AWS"
          command: ./aws_setup.sh
      - run:
          name: 'Deploy Dev'
          command: STAGE=dev make
  deploy_prod:
    docker:
      - image: guildeducation/node-lambda:latest
    working_directory: *dir
    steps:
      - checkout
      - run:
          name: "Install tools"
          command: apt-get update && apt-get install -y rsync
      - run:
          name: "Setup Path"
          command: echo 'export PATH=~/.local/bin/:$PATH' >> $BASH_ENV
      - run:
          name: "Configure AWS"
          command: ./aws_setup.sh
      - run:
          name: 'Deploy Prod'
          command: STAGE=prod make

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - deploy_prod:
          requires:
            - test
          filters:
            branches:
              only:
                - master
